using System.Security.Cryptography;

namespace zfile
{
    public class FileSystemCalcChecksumOperation : FileSourceCalcChecksumOperation
    {
        private FileEntries fullFilesTree;  // 源文件，包括子目录中的所有文件/目录
        private FileSourceCalcChecksumOperationStatistics statistics; // 统计信息的本地副本
        private List<string> checkSumFile;
        private byte[] buffer;
        private List<ChecksumEntry> checksumsList;

        // 选项
        private FileSourceOperationOptionFileExists fileExistsOption;
        private FileSourceOperationOptionSymLink symLinkOption;
        private bool skipErrors;

        public FileSystemCalcChecksumOperation(IFileSource targetFileSource, 
            FileEntries files, 
            string targetPath, 
            string targetMask)
            : base(targetFileSource, files, targetPath, targetMask)
        {
            buffer = null;
            symLinkOption = FileSourceOperationOptionSymLink.None;
            fileExistsOption = FileSourceOperationOptionFileExists.None;
            skipErrors = false;
            fullFilesTree = new FileEntries();
            checkSumFile = new List<string>();
            checksumsList = new List<ChecksumEntry>();
        }

        protected override void Initialize()
        {
            // 获取初始化的统计信息；然后我们只更改需要的内容
            statistics = RetrieveStatistics();

            switch (Mode)
            {
                case CalcCheckSumOperationMode.Calc:
                    FillAndCount(Files, false, false,
                        fullFilesTree,
                        ref statistics.TotalFiles,
                        ref statistics.TotalBytes);     // 获取完整的文件列表（递归）

                    if (Algorithm == HashAlgorithm.SFV && OneFile)
                    {
                        checkSumFile.Add("; Generated by WIN-SFV32 v1.0");
                        checkSumFile.Add("; (Compatible: Double Commander)");
                    }
                    break;
                case CalcCheckSumOperationMode.Verify:
                    InitializeVerifyMode();
                    break;
            }

            buffer = new byte[GlobalSettings.HashBlockSize];
        }

        private void InitializeVerifyMode()
        {
            // 实现验证模式的初始化
            // TODO: 实现验证模式的初始化逻辑
        }

        protected override void MainExecute()
        {
            string targetFileName = null;
            if (OneFile && Mode == CalcCheckSumOperationMode.Calc)
            {
                targetFileName = TargetMask;
                switch (FileExists(targetFileName))
                {
                    case FileSourceOperationOptionFileExists.Skip:
                        return;
                    case FileSourceOperationOptionFileExists.Overwrite:
                        break;
                }
            }

            for (int currentFileIndex = 0; currentFileIndex < fullFilesTree.Count; currentFileIndex++)
            {
                var file = fullFilesTree[currentFileIndex];

                statistics.CurrentFile = file.FullName;
                statistics.CurrentFileTotalBytes = file.Length;
                statistics.CurrentFileDoneBytes = 0;

                UpdateStatistics(statistics);

                if (!(file.Attributes.HasFlag(FileAttributes.Directory) || 
                      file.Attributes.HasFlag(FileAttributes.ReparsePoint)))
                {
                    long oldDoneBytes = statistics.DoneBytes;

                    switch (Mode)
                    {
                        case CalcCheckSumOperationMode.Calc:
                            CalcChecksumProcessFile(file);
                            break;
                        case CalcCheckSumOperationMode.Verify:
                            var entry = checksumsList[currentFileIndex];
                            Algorithm = entry.Algorithm;
                            VerifyChecksumProcessFile(file, entry.Checksum);
                            break;
                    }

                    statistics.DoneFiles++;
                    statistics.DoneBytes = oldDoneBytes + file.Length;

                    UpdateStatistics(statistics);
                }

                CheckOperationState();
            }

            switch (Mode)
            {
                case CalcCheckSumOperationMode.Calc:
                    if (OneFile)
                    {
                        try
                        {
                            int currentFileIndex = (Algorithm == HashAlgorithm.SFV) ? 2 : 0;
                            if (checkSumFile.Count > currentFileIndex)
                            {
                                File.WriteAllLines(targetFileName, checkSumFile);
                            }
                        }
                        catch (Exception ex) when (ex is UnauthorizedAccessException || ex is IOException)
                        {
                            ShowMessage($"无法创建/写入文件 {targetFileName}: {ex.Message}");
                        }
                    }
                    break;
                case CalcCheckSumOperationMode.Verify:
                    // 验证模式的处理
                    break;
            }
        }

        private bool CalcChecksumProcessFile(FileEntry file)
        {
            try
            {
                using (var stream = file.OpenRead())
                {
                    string checksum;
                    if (CalculateChecksum(stream, out checksum))
                    {
                        AddFile(file.DirectoryName, file.Name, checksum);
                        return true;
                    }
                }
            }
            catch (Exception ex)
            {
                LogMessage($"计算校验和时出错: {ex.Message}", LogOption.Error);
            }
            return false;
        }

        private bool VerifyChecksumProcessFile(FileEntry file, string expectedChecksum)
        {
            try
            {
                using (var stream = file.OpenRead())
                {
                    string actualChecksum;
                    if (CalculateChecksum(stream, out actualChecksum))
                    {
                        bool result = string.Equals(actualChecksum, expectedChecksum, StringComparison.OrdinalIgnoreCase);
                        LogMessage($"验证 {file.Name}: {(result ? "成功" : "失败")}", 
                            result ? LogOption.Success : LogOption.Error);
                        return result;
                    }
                }
            }
            catch (Exception ex)
            {
                LogMessage($"验证校验和时出错: {ex.Message}", LogOption.Error);
            }
            return false;
        }

        private void AddFile(string path, string fileName, string hash)
        {
            try
            {
                var fileToVerify = new FileEntry(Path.Combine(path, fileName));
                if (!(fileToVerify.Attributes.HasFlag(FileAttributes.Directory) || 
                      fileToVerify.Attributes.HasFlag(FileAttributes.ReparsePoint)))
                {
                    statistics.TotalFiles++;
                    statistics.TotalBytes += fileToVerify.Length;

                    fullFilesTree.Add(fileToVerify);
                    var entry = new ChecksumEntry
                    {
                        Checksum = hash,
                        Algorithm = Algorithm
                    };
                    checksumsList.Add(entry);
                }
            }
            catch (FileNotFoundException)
            {
                LogMessage($"文件未找到: {fileName}", LogOption.Error);
            }
        }

        private bool CalculateChecksum(Stream stream, out string checksum)
        {
            checksum = null;
            try
            {
                using (var hashAlgorithm = GetHashAlgorithm(Algorithm))
                {
                    byte[] hash = hashAlgorithm.ComputeHash(stream);
                    checksum = BitConverter.ToString(hash).Replace("-", "").ToLower();
                    return true;
                }
            }
            catch (Exception ex)
            {
                LogMessage($"计算校验和时出错: {ex.Message}", LogOption.Error);
                return false;
            }
        }

        private HashAlgorithm GetHashAlgorithm(HashAlgorithm algorithm)
        {
            switch (algorithm)
            {
                case HashAlgorithm.MD5:
                    return MD5.Create();
                case HashAlgorithm.SHA1:
                    return SHA1.Create();
                case HashAlgorithm.SHA256:
                    return SHA256.Create();
                case HashAlgorithm.SHA512:
                    return SHA512.Create();
                default:
                    throw new NotSupportedException($"不支持的哈希算法: {algorithm}");
            }
        }

        private void LogMessage(string message, LogOption options)
        {
            // TODO: 实现日志记录
        }

        private FileSourceOperationOptionFileExists FileExists(string fileName)
        {
            if (File.Exists(fileName))
            {
                return fileExistsOption;
            }
            return FileSourceOperationOptionFileExists.None;
        }
    }

    public class ChecksumEntry
    {
        public string Checksum { get; set; }
        public HashAlgorithm Algorithm { get; set; }
    }

 
} 