services:
  filezilla:
    build:
      context: .
      network: host
    restart: unless-stopped
    ports:
      - 0.0.0.0:20:20
      - 0.0.0.0:21:21
      - 0.0.0.0:14149:14149
      - 21100-21110:21100-21199
    volumes:
      - ./home:/home/filezilla
      - ./logs:/var/log/filezilla
